kafka:
  brokers:
    - kafka:9092
  version: 4.0.0
  assignor: roundrobin
  oldest: false
  verbose: true
runner:
  heartbeat_interval: 3
  frame_interval_millis: 3000
  heartbeat_url: orchestrator:8080/ping
  terminate_url: orchestrator:8080/term
  heartbeat_tries: 5