kafka:
  brokers:
    - kafka:9092
  version: 4.0.0
  assignor: roundrobin
  oldest: false
  verbose: true
  topic: videos
postgresql:
  DATABASE_PORT: 5432
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password
  DATABASE_NAME: scenarios
  DATABASE_HOST: inference_db
  max_attempts: 5
server:
  port: 8080